<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Operations;

use \speakeasy_bar-test\Risk-Cloud-API\Utils\SpeakeasyMetadata;
class CreateWorkflowMapRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiCreateIn $workflowMapApiCreateIn;
    
	public function __construct()
	{
		$this->workflowMapApiCreateIn = new \speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiCreateIn();
	}
}
