<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Operations;

use \speakeasy_bar-test\Risk-Cloud-API\Utils\SpeakeasyMetadata;
class CreateWorkflowRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \speakeasy_bar-test\Risk-Cloud-API\Models\Components\WorkflowApiCreateIn $workflowApiCreateIn;
    
	public function __construct()
	{
		$this->workflowApiCreateIn = new \speakeasy_bar-test\Risk-Cloud-API\Models\Components\WorkflowApiCreateIn();
	}
}
