<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Operations;

use \speakeasy_bar-test\Risk-Cloud-API\Utils\SpeakeasyMetadata;
class GetApiTokenSecurity
{
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=basic,name=password')]
    public string $password;
    
	#[SpeakeasyMetadata('security:scheme=true,type=http,subtype=basic,name=username')]
    public string $username;
    
	public function __construct()
	{
		$this->password = "";
		$this->username = "";
	}
}
