<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Operations;

use \speakeasy_bar-test\Risk-Cloud-API\Utils\SpeakeasyMetadata;
class ReadAllStepsRequest
{
    /**
     * The zero-indexed page number (must not be less than 0, defaults to 0)
     * 
     * @var ?int $page
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;
    
    /**
     * The size of the page and maximum number of items to be returned (must not be less than 1, defaults to 20)
     * 
     * @var ?int $size
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=size')]
    public ?int $size = null;
    
    /**
     * The unique ID of a workflow where, if provided, the response will only contain steps from the identified workflow
     * 
     * @var ?string $workflowId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=workflow-id')]
    public ?string $workflowId = null;
    
	public function __construct()
	{
		$this->page = null;
		$this->size = null;
		$this->workflowId = null;
	}
}
