<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Operations;

use \speakeasy_bar-test\Risk-Cloud-API\Utils\SpeakeasyMetadata;
class ReadAllApplicationsRequest
{
    /**
     * The zero-indexed page number (must not be less than 0, defaults to 0)
     * 
     * @var ?int $page
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;
    
    /**
     * The size of the page and maximum number of items to be returned (must not be less than 1, defaults to 20)
     * 
     * @var ?int $size
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=size')]
    public ?int $size = null;
    
	public function __construct()
	{
		$this->page = null;
		$this->size = null;
	}
}
