<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Operations;

use \speakeasy_bar-test\Risk-Cloud-API\Utils\SpeakeasyMetadata;
class ReadAllWorkflowsRequest
{
    /**
     * The unique ID of a parent application where, if provided, the response will only contain workflows from the identified application
     * 
     * @var ?string $applicationId
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=application-id')]
    public ?string $applicationId = null;
    
    /**
     * Whether [Jira workflows](https://help.logicgate.com/hc/en-us) are to be included in the response in addition to regular workflows (defaults to true)
     * 
     * @var ?bool $includeJiraWorkflows
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=include-jira-workflows')]
    public ?bool $includeJiraWorkflows = null;
    
    /**
     * The zero-indexed page number (must not be less than 0, defaults to 0)
     * 
     * @var ?int $page
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=page')]
    public ?int $page = null;
    
    /**
     * The size of the page and maximum number of items to be returned (must not be less than 1, defaults to 20)
     * 
     * @var ?int $size
     */
	#[SpeakeasyMetadata('queryParam:style=form,explode=true,name=size')]
    public ?int $size = null;
    
	public function __construct()
	{
		$this->applicationId = null;
		$this->includeJiraWorkflows = null;
		$this->page = null;
		$this->size = null;
	}
}
