<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Operations;

use \speakeasy_bar-test\Risk-Cloud-API\Utils\SpeakeasyMetadata;
class UpdateRequest
{
	#[SpeakeasyMetadata('request:mediaType=application/json')]
    public \speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiUpdateIn $stepApiUpdateIn;
    
    /**
     * The unique ID of the step
     * 
     * @var string $id
     */
	#[SpeakeasyMetadata('pathParam:style=simple,explode=false,name=id')]
    public string $id;
    
	public function __construct()
	{
		$this->stepApiUpdateIn = new \speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiUpdateIn();
		$this->id = "";
	}
}
