<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/** The type of Risk Cloud application */
enum ApplicationPropertyApiOutType: string
{
    case AccessManagement = 'ACCESS_MANAGEMENT';
    case AmlKyc = 'AML_KYC';
    case AssetManagement = 'ASSET_MANAGEMENT';
    case AuditManagement = 'AUDIT_MANAGEMENT';
    case BusinessContinuityPlanning = 'BUSINESS_CONTINUITY_PLANNING';
    case ChangeManagement = 'CHANGE_MANAGEMENT';
    case ComplaintManagement = 'COMPLAINT_MANAGEMENT';
    case ComplianceManagement = 'COMPLIANCE_MANAGEMENT';
    case ContractManagement = 'CONTRACT_MANAGEMENT';
    case ControlsCompliance = 'CONTROLS_COMPLIANCE';
    case ControlsManagement = 'CONTROLS_MANAGEMENT';
    case CrisisManagement = 'CRISIS_MANAGEMENT';
    case Custom = 'CUSTOM';
    case CustomGrcUseCase = 'CUSTOM_GRC_USE_CASE';
    case CyberRiskManagement = 'CYBER_RISK_MANAGEMENT';
    case DataPrivacyManagement = 'DATA_PRIVACY_MANAGEMENT';
    case EmployeeCompliance = 'EMPLOYEE_COMPLIANCE';
    case EnterpriseRiskManagement = 'ENTERPRISE_RISK_MANAGEMENT';
    case Esg = 'ESG';
    case IncidentManagement = 'INCIDENT_MANAGEMENT';
    case InternalAuditManagement = 'INTERNAL_AUDIT_MANAGEMENT';
    case ItRiskManagement = 'IT_RISK_MANAGEMENT';
    case None = 'NONE';
    case OperationalResiliency = 'OPERATIONAL_RESILIENCY';
    case Other = 'OTHER';
    case PolicyAndProcedureManagement = 'POLICY_AND_PROCEDURE_MANAGEMENT';
    case PolicyManagement = 'POLICY_MANAGEMENT';
    case PrivacyManagement = 'PRIVACY_MANAGEMENT';
    case Quantify = 'QUANTIFY';
    case RegulatoryCompliance = 'REGULATORY_COMPLIANCE';
    case Repository = 'REPOSITORY';
    case RiskQuantification = 'RISK_QUANTIFICATION';
    case SoxTesting = 'SOX_TESTING';
    case StandardsRegulations = 'STANDARDS_REGULATIONS';
    case Survey = 'SURVEY';
    case ThirdPartyRiskManagement = 'THIRD_PARTY_RISK_MANAGEMENT';
}
