<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/** The icon type of the application (defaults to CUBES) */
enum ApplicationApiCreateInIcon: string
{
    case Bookmark = 'BOOKMARK';
    case Bolt = 'BOLT';
    case Bullhorn = 'BULLHORN';
    case Certificate = 'CERTIFICATE';
    case CheckSquareO = 'CHECK_SQUARE_O';
    case Cloud = 'CLOUD';
    case Comments = 'COMMENTS';
    case Cubes = 'CUBES';
    case Dollar = 'DOLLAR';
    case ExclamationTriangle = 'EXCLAMATION_TRIANGLE';
    case TextO = 'TEXT_O';
    case Folder = 'FOLDER';
    case Gift = 'GIFT';
    case Globe = 'GLOBE';
    case Heartbeat = 'HEARTBEAT';
    case Leaf = 'LEAF';
    case Legal = 'LEGAL';
    case LifeRing = 'LIFE_RING';
    case Medkit = 'MEDKIT';
    case Money = 'MONEY';
    case Percent = 'PERCENT';
    case Rocket = 'ROCKET';
    case Signal = 'SIGNAL';
    case University = 'UNIVERSITY';
    case UserCircle = 'USER_CIRCLE';
}
