<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


class ApplicationApiUpdateIn
{
    /**
     * The hex representation of the icon color of the application
     * 
     * @var ?string $color
     */
	#[\JMS\Serializer\Annotation\SerializedName('color')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $color = null;
    
    /**
     * The icon type of the application
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\ApplicationApiUpdateInIcon $icon
     */
	#[\JMS\Serializer\Annotation\SerializedName('icon')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\ApplicationApiUpdateInIcon>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ApplicationApiUpdateInIcon $icon = null;
    
    /**
     * Whether the application is live
     * 
     * @var ?bool $live
     */
	#[\JMS\Serializer\Annotation\SerializedName('live')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $live = null;
    
    /**
     * The name of the application
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Whether users with the Build entitlement must be explicitly granted permission to edit this application
     * 
     * @var ?bool $restrictBuildAccess
     */
	#[\JMS\Serializer\Annotation\SerializedName('restrictBuildAccess')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $restrictBuildAccess = null;
    
    /**
     * The type of Risk Cloud application
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\ApplicationApiUpdateInType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\ApplicationApiUpdateInType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ApplicationApiUpdateInType $type = null;
    
	public function __construct()
	{
		$this->color = null;
		$this->icon = null;
		$this->live = null;
		$this->name = null;
		$this->restrictBuildAccess = null;
		$this->type = null;
	}
}
