<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/** The type of the field */
enum FieldRecordApiOutFieldType: string
{
    case Date = 'DATE';
    case User = 'USER';
    case ExternalUser = 'EXTERNAL_USER';
    case Text = 'TEXT';
    case TextArea = 'TEXT_AREA';
    case Number = 'NUMBER';
    case ESignature = 'E_SIGNATURE';
    case Checkbox = 'CHECKBOX';
    case MultiSelect = 'MULTI_SELECT';
    case Radio = 'RADIO';
    case Select = 'SELECT';
    case Attachment = 'ATTACHMENT';
    case Calculation = 'CALCULATION';
    case DateCalculation = 'DATE_CALCULATION';
    case Other = 'OTHER';
}
