<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


class LegacyApiTokenOut
{
    /**
     * An API access token to be used within the bearer authorization header of subsequent Risk Cloud API requests
     * 
     * @var ?string $accessToken
     */
	#[\JMS\Serializer\Annotation\SerializedName('access_token')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $accessToken = null;
    
    /**
     * The remaining time in seconds until the token expires
     * 
     * @var ?int $expiresIn
     */
	#[\JMS\Serializer\Annotation\SerializedName('expires_in')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $expiresIn = null;
    
    /**
     * The privilege scope of the token, expected to be "read write" for the Risk Cloud API
     * 
     * @var ?string $scope
     */
	#[\JMS\Serializer\Annotation\SerializedName('scope')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $scope = null;
    
    /**
     * The token type, expected to be "bearer" for the Risk Cloud API
     * 
     * @var ?string $tokenType
     */
	#[\JMS\Serializer\Annotation\SerializedName('token_type')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $tokenType = null;
    
	public function __construct()
	{
		$this->accessToken = null;
		$this->expiresIn = null;
		$this->scope = null;
		$this->tokenType = null;
	}
}
