<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/**
 * PageLinksOut - A collection of page URL links for navigation and iteration
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Shared
 * @access public
 */
class PageLinksOut
{
    /**
     * A URL path to the first page of requested data
     * 
     * @var ?string $first
     */
	#[\JMS\Serializer\Annotation\SerializedName('first')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $first = null;
    
    /**
     * A URL link to the last page of requested data
     * 
     * @var ?string $last
     */
	#[\JMS\Serializer\Annotation\SerializedName('last')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $last = null;
    
    /**
     * A URL link to the next page of requested data or `null` if currently on last page
     * 
     * @var ?string $next
     */
	#[\JMS\Serializer\Annotation\SerializedName('next')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $next = null;
    
    /**
     * A URL path to the next page of requested data or `null` if currently on first page
     * 
     * @var ?string $prev
     */
	#[\JMS\Serializer\Annotation\SerializedName('prev')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $prev = null;
    
    /**
     * A URL path to the current page of requested data
     * 
     * @var ?string $self
     */
	#[\JMS\Serializer\Annotation\SerializedName('self')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $self = null;
    
	public function __construct()
	{
		$this->first = null;
		$this->last = null;
		$this->next = null;
		$this->prev = null;
		$this->self = null;
	}
}
