<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/**
 * RecordApiOut - A array of returned items
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Shared
 * @access public
 */
class RecordApiOut
{
    /**
     * The parent application of the record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\ApplicationPropertyApiOut $application
     */
	#[\JMS\Serializer\Annotation\SerializedName('application')]
    #[\JMS\Serializer\Annotation\Type('speakeasy_bar-test\Risk-Cloud-API\Models\Shared\ApplicationPropertyApiOut')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?ApplicationPropertyApiOut $application = null;
    
    /**
     * The creator of the record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\UserPropertyApiOut $assignee
     */
	#[\JMS\Serializer\Annotation\SerializedName('assignee')]
    #[\JMS\Serializer\Annotation\Type('speakeasy_bar-test\Risk-Cloud-API\Models\Shared\UserPropertyApiOut')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UserPropertyApiOut $assignee = null;
    
    /**
     * The creator of the record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\UserPropertyApiOut $creator
     */
	#[\JMS\Serializer\Annotation\SerializedName('creator')]
    #[\JMS\Serializer\Annotation\Type('speakeasy_bar-test\Risk-Cloud-API\Models\Shared\UserPropertyApiOut')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?UserPropertyApiOut $creator = null;
    
    /**
     * The origin step of the record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepPropertyApiOut $currentStep
     */
	#[\JMS\Serializer\Annotation\SerializedName('currentStep')]
    #[\JMS\Serializer\Annotation\Type('speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepPropertyApiOut')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StepPropertyApiOut $currentStep = null;
    
    /**
     * Date information associated with the record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\RecordDatesApiOut $dates
     */
	#[\JMS\Serializer\Annotation\SerializedName('dates')]
    #[\JMS\Serializer\Annotation\Type('speakeasy_bar-test\Risk-Cloud-API\Models\Shared\RecordDatesApiOut')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?RecordDatesApiOut $dates = null;
    
    /**
     * The fields and values of the record
     * 
     * @var ?array<\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\FieldRecordApiOut> $fields
     */
	#[\JMS\Serializer\Annotation\SerializedName('fields')]
    #[\JMS\Serializer\Annotation\Type('array<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\FieldRecordApiOut>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $fields = null;
    
    /**
     * The unique ID of this Risk Cloud resource
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * The text value of the primary field of the record, otherwise the workflow prefix and sequence number of the record
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Identifies the type of object this data represents
     * 
     * @var ?string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $object = null;
    
    /**
     * The origin step of the record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepPropertyApiOut $originStep
     */
	#[\JMS\Serializer\Annotation\SerializedName('originStep')]
    #[\JMS\Serializer\Annotation\Type('speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepPropertyApiOut')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StepPropertyApiOut $originStep = null;
    
    /**
     * The workflow prefix and sequence number of the record
     * 
     * @var ?string $recordName
     */
	#[\JMS\Serializer\Annotation\SerializedName('recordName')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $recordName = null;
    
    /**
     * The sequence number of the record
     * 
     * @var ?int $sequenceNumber
     */
	#[\JMS\Serializer\Annotation\SerializedName('sequenceNumber')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $sequenceNumber = null;
    
    /**
     * The status of the record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\RecordApiOutStatus $status
     */
	#[\JMS\Serializer\Annotation\SerializedName('status')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\RecordApiOutStatus>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?RecordApiOutStatus $status = null;
    
    /**
     * The parent workflow of the step
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowPropertyApiOut $workflow
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow')]
    #[\JMS\Serializer\Annotation\Type('speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowPropertyApiOut')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?WorkflowPropertyApiOut $workflow = null;
    
	public function __construct()
	{
		$this->application = null;
		$this->assignee = null;
		$this->creator = null;
		$this->currentStep = null;
		$this->dates = null;
		$this->fields = null;
		$this->id = null;
		$this->name = null;
		$this->object = null;
		$this->originStep = null;
		$this->recordName = null;
		$this->sequenceNumber = null;
		$this->status = null;
		$this->workflow = null;
	}
}
