<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;

use \speakeasy_bar-test\Risk-Cloud-API\Utils\SpeakeasyMetadata;
class SchemeBasic
{
	#[SpeakeasyMetadata('security:name=password')]
    public string $password;
    
	#[SpeakeasyMetadata('security:name=username')]
    public string $username;
    
	public function __construct()
	{
		$this->password = "";
		$this->username = "";
	}
}
