<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/**
 * StepApiCreateIn - Step (Create)
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Shared
 * @access public
 */
class StepApiCreateIn
{
    /**
     * Indicates which users are allowed to be assigned this step on a record (defaults to APP_USERS)
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiCreateInAssignableUserType $assignableUserType
     */
	#[\JMS\Serializer\Annotation\SerializedName('assignableUserType')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiCreateInAssignableUserType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StepApiCreateInAssignableUserType $assignableUserType = null;
    
    /**
     * Whether comments are displayed on a step (defaults to false)
     * 
     * @var ?bool $enableComments
     */
	#[\JMS\Serializer\Annotation\SerializedName('enableComments')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $enableComments = null;
    
    /**
     * Whether MFA is required for external users to access this step. (defaults to false)
     * 
     * @var ?bool $externalUserMfaRequired
     */
	#[\JMS\Serializer\Annotation\SerializedName('externalUserMfaRequired')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $externalUserMfaRequired = null;
    
    /**
     * The name of the step
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The unique ID of the parent workflow of the step
     * 
     * @var string $workflowId
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflowId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $workflowId;
    
    /**
     * The x-coordinate of the step in the application builder (must not be less than 0, defaults to 0)
     * 
     * @var ?int $xpos
     */
	#[\JMS\Serializer\Annotation\SerializedName('xpos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $xpos = null;
    
    /**
     * The y-coordinate of the step in the application builder (must not be less than 0, defaults to 0)
     * 
     * @var ?int $ypos
     */
	#[\JMS\Serializer\Annotation\SerializedName('ypos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ypos = null;
    
	public function __construct()
	{
		$this->assignableUserType = null;
		$this->enableComments = null;
		$this->externalUserMfaRequired = null;
		$this->name = "";
		$this->workflowId = "";
		$this->xpos = null;
		$this->ypos = null;
	}
}
