<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/** Indicates which users are allowed to be assigned this step on a record */
enum StepApiUpdateInAssignableUserType: string
{
    case AppAndExternalUsers = 'APP_AND_EXTERNAL_USERS';
    case AppUsers = 'APP_USERS';
    case ExternalUsers = 'EXTERNAL_USERS';
}
