<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


class StepApiOut
{
    /**
     * Indicates which users are allowed to be assigned this step on a record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiOutAssignableUserType $assignableUserType
     */
	#[\JMS\Serializer\Annotation\SerializedName('assignableUserType')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiOutAssignableUserType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StepApiOutAssignableUserType $assignableUserType = null;
    
    /**
     * Whether comments are displayed on a step
     * 
     * @var ?bool $enableComments
     */
	#[\JMS\Serializer\Annotation\SerializedName('enableComments')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $enableComments = null;
    
    /**
     * Whether MFA is required for external users to access this step.
     * 
     * @var ?bool $externalUserMfaRequired
     */
	#[\JMS\Serializer\Annotation\SerializedName('externalUserMfaRequired')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $externalUserMfaRequired = null;
    
    /**
     * The unique ID of this Risk Cloud resource
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * The name of the step
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Identifies the type of object this data represents
     * 
     * @var ?string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $object = null;
    
    /**
     * The type of the step
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiOutType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiOutType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StepApiOutType $type = null;
    
    /**
     * The parent workflow of the step
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowPropertyApiOut $workflow
     */
	#[\JMS\Serializer\Annotation\SerializedName('workflow')]
    #[\JMS\Serializer\Annotation\Type('speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowPropertyApiOut')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?WorkflowPropertyApiOut $workflow = null;
    
    /**
     * The x-coordinate of the step in the application builder
     * 
     * @var ?int $xpos
     */
	#[\JMS\Serializer\Annotation\SerializedName('xpos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $xpos = null;
    
    /**
     * The y-coordinate of the step in the application builder
     * 
     * @var ?int $ypos
     */
	#[\JMS\Serializer\Annotation\SerializedName('ypos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ypos = null;
    
	public function __construct()
	{
		$this->assignableUserType = null;
		$this->enableComments = null;
		$this->externalUserMfaRequired = null;
		$this->id = null;
		$this->name = null;
		$this->object = null;
		$this->type = null;
		$this->workflow = null;
		$this->xpos = null;
		$this->ypos = null;
	}
}
