<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/**
 * WorkflowMapApiCreateIn - Workflow Map (Create)
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Shared
 * @access public
 */
class WorkflowMapApiCreateIn
{
    /**
     * The unique ID of the source workflow of the workflow map relationship
     * 
     * @var string $from
     */
	#[\JMS\Serializer\Annotation\SerializedName('from')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $from;
    
    /**
     * The type of the relationship between workflows
     * 
     * @var \speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiCreateInRelationship $relationship
     */
	#[\JMS\Serializer\Annotation\SerializedName('relationship')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiCreateInRelationship>')]
    public WorkflowMapApiCreateInRelationship $relationship;
    
    /**
     * The unique ID of the destination workflow of the workflow map relationship
     * 
     * @var string $to
     */
	#[\JMS\Serializer\Annotation\SerializedName('to')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $to;
    
	public function __construct()
	{
		$this->from = "";
		$this->relationship = \speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiCreateInRelationship::OneToOne;
		$this->to = "";
	}
}
