<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


class WorkflowApiOut
{
    /**
     * The unique ID of the parent application of the workflow
     * 
     * @var ?string $applicationId
     */
	#[\JMS\Serializer\Annotation\SerializedName('applicationId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $applicationId = null;
    
    /**
     * The unique ID of this Risk Cloud resource
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * The name of the workflow
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Identifies the type of object this data represents
     * 
     * @var ?string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $object = null;
    
    /**
     * The prefix to be used in the name of every record created from this workflow
     * 
     * @var ?string $recordPrefix
     */
	#[\JMS\Serializer\Annotation\SerializedName('recordPrefix')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $recordPrefix = null;
    
    /**
     * The x-coordinate of the workflow in the application builder
     * 
     * @var ?int $xpos
     */
	#[\JMS\Serializer\Annotation\SerializedName('xpos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $xpos = null;
    
    /**
     * The y-coordinate of the workflow in the application builder
     * 
     * @var ?int $ypos
     */
	#[\JMS\Serializer\Annotation\SerializedName('ypos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ypos = null;
    
	public function __construct()
	{
		$this->applicationId = null;
		$this->id = null;
		$this->name = null;
		$this->object = null;
		$this->recordPrefix = null;
		$this->xpos = null;
		$this->ypos = null;
	}
}
