<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/** The type of the relationship between workflows */
enum WorkflowMapApiOutRelationship: string
{
    case OneToOne = 'OneToOne';
    case OneToMany = 'OneToMany';
    case ManyToOne = 'ManyToOne';
    case ManyToMany = 'ManyToMany';
}
