<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


class WorkflowMapApiOut
{
    /**
     * The unique ID of the source workflow of the workflow map relationship
     * 
     * @var ?string $from
     */
	#[\JMS\Serializer\Annotation\SerializedName('from')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $from = null;
    
    /**
     * The unique ID of this Risk Cloud resource
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * Identifies the type of object this data represents
     * 
     * @var ?string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $object = null;
    
    /**
     * The type of the relationship between workflows
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiOutRelationship $relationship
     */
	#[\JMS\Serializer\Annotation\SerializedName('relationship')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiOutRelationship>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?WorkflowMapApiOutRelationship $relationship = null;
    
    /**
     * The unique ID of the destination workflow of the workflow map relationship
     * 
     * @var ?string $to
     */
	#[\JMS\Serializer\Annotation\SerializedName('to')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $to = null;
    
	public function __construct()
	{
		$this->from = null;
		$this->id = null;
		$this->object = null;
		$this->relationship = null;
		$this->to = null;
	}
}
