<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/**
 * WorkflowApiCreateIn - Workflow (Create)
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Shared
 * @access public
 */
class WorkflowApiCreateIn
{
    /**
     * The unique ID of the parent application of the workflow
     * 
     * @var string $applicationId
     */
	#[\JMS\Serializer\Annotation\SerializedName('applicationId')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $applicationId;
    
    /**
     * The name of the workflow
     * 
     * @var string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $name;
    
    /**
     * The prefix to be used in the name of every record created from this workflow
     * 
     * @var string $recordPrefix
     */
	#[\JMS\Serializer\Annotation\SerializedName('recordPrefix')]
    #[\JMS\Serializer\Annotation\Type('string')]
    public string $recordPrefix;
    
    /**
     * The x-coordinate of the workflow in the application builder (must not be less than 0, defaults to 0)
     * 
     * @var ?int $xpos
     */
	#[\JMS\Serializer\Annotation\SerializedName('xpos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $xpos = null;
    
    /**
     * The y-coordinate of the workflow in the application builder (must not be less than 0, defaults to 0)
     * 
     * @var ?int $ypos
     */
	#[\JMS\Serializer\Annotation\SerializedName('ypos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ypos = null;
    
	public function __construct()
	{
		$this->applicationId = "";
		$this->name = "";
		$this->recordPrefix = "";
		$this->xpos = null;
		$this->ypos = null;
	}
}
