<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Shared;


/**
 * WorkflowApiUpdateIn - Workflow (Update)
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Shared
 * @access public
 */
class WorkflowApiUpdateIn
{
    /**
     * The name of the workflow
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * The prefix to be used in the name of every record created from this workflow
     * 
     * @var ?string $recordPrefix
     */
	#[\JMS\Serializer\Annotation\SerializedName('recordPrefix')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $recordPrefix = null;
    
    /**
     * The x-coordinate of the workflow in the application builder (must not be less than 0)
     * 
     * @var ?int $xpos
     */
	#[\JMS\Serializer\Annotation\SerializedName('xpos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $xpos = null;
    
    /**
     * The y-coordinate of the workflow in the application builder (must not be less than 0)
     * 
     * @var ?int $ypos
     */
	#[\JMS\Serializer\Annotation\SerializedName('ypos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ypos = null;
    
	public function __construct()
	{
		$this->name = null;
		$this->recordPrefix = null;
		$this->xpos = null;
		$this->ypos = null;
	}
}
