<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Components;


/**
 * FieldRecordApiOut - The fields and values of the record
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Components
 * @access public
 */
class FieldRecordApiOut
{
    /**
     * Whether the field is global
     * 
     * @var ?bool $global
     */
	#[\JMS\Serializer\Annotation\SerializedName('global')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $global = null;
    
    /**
     * The unique ID of this Risk Cloud resource
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * The label of the field as shown on the record
     * 
     * @var ?string $label
     */
	#[\JMS\Serializer\Annotation\SerializedName('label')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $label = null;
    
    /**
     * The name of the field
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Identifies the type of object this data represents
     * 
     * @var ?string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $object = null;
    
    /**
     * The type of the field
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Components\FieldRecordApiOutFieldType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Components\FieldRecordApiOutFieldType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?FieldRecordApiOutFieldType $type = null;
    
    /**
     * The type of the field value
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Components\FieldRecordApiOutValueType $valueType
     */
	#[\JMS\Serializer\Annotation\SerializedName('valueType')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Components\FieldRecordApiOutValueType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?FieldRecordApiOutValueType $valueType = null;
    
    /**
     * The values of the record field
     * 
     * @var ?array<\speakeasy_bar-test\Risk-Cloud-API\Models\Components\ValuePropertyApiOut> $values
     */
	#[\JMS\Serializer\Annotation\SerializedName('values')]
    #[\JMS\Serializer\Annotation\Type('array<speakeasy_bar-test\Risk-Cloud-API\Models\Components\ValuePropertyApiOut>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?array $values = null;
    
	public function __construct()
	{
		$this->global = null;
		$this->id = null;
		$this->label = null;
		$this->name = null;
		$this->object = null;
		$this->type = null;
		$this->valueType = null;
		$this->values = null;
	}
}
