<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Components;


/**
 * PageInfoOut - A collection page metadata
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Components
 * @access public
 */
class PageInfoOut
{
    /**
     * The zero-indexed page number (must not be less than 0, defaults to 0)
     * 
     * @var ?int $number
     */
	#[\JMS\Serializer\Annotation\SerializedName('number')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $number = null;
    
    /**
     * The size of the page and maximum number of items to be returned (must not be less than 1, defaults to 20)
     * 
     * @var ?int $size
     */
	#[\JMS\Serializer\Annotation\SerializedName('size')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $size = null;
    
    /**
     * The total number of items available
     * 
     * @var ?int $totalElements
     */
	#[\JMS\Serializer\Annotation\SerializedName('totalElements')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $totalElements = null;
    
    /**
     * The total number of pages available based on the size
     * 
     * @var ?int $totalPages
     */
	#[\JMS\Serializer\Annotation\SerializedName('totalPages')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $totalPages = null;
    
	public function __construct()
	{
		$this->number = null;
		$this->size = null;
		$this->totalElements = null;
		$this->totalPages = null;
	}
}
