<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Components;


/**
 * RecordDatesApiOut - Date information associated with the record
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Components
 * @access public
 */
class RecordDatesApiOut
{
    /**
     * The moment this record was completed if the record is currently in an end step measured in milliseconds since the Unix epoch
     * 
     * @var ?\DateTime $completed
     */
	#[\JMS\Serializer\Annotation\SerializedName('completed')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $completed = null;
    
    /**
     * The moment this Risk Cloud resource was created measured in milliseconds since the Unix epoch.
     * 
     * @var ?\DateTime $created
     */
	#[\JMS\Serializer\Annotation\SerializedName('created')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $created = null;
    
    /**
     * The number of days until this record is due
     * 
     * @var ?int $daysUntilDue
     */
	#[\JMS\Serializer\Annotation\SerializedName('daysUntilDue')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $daysUntilDue = null;
    
    /**
     * The due date of this record and step SLA measured in milliseconds since the Unix epoch
     * 
     * @var ?\DateTime $dueDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('dueDate')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $dueDate = null;
    
    /**
     * The moment this record was last completed regardless of if the record has transitioned from an end step measured in milliseconds since the Unix epoch
     * 
     * @var ?\DateTime $lastCompleted
     */
	#[\JMS\Serializer\Annotation\SerializedName('lastCompleted')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $lastCompleted = null;
    
    /**
     * The due date of this record measured in milliseconds since the Unix epoch
     * 
     * @var ?\DateTime $recordDueDate
     */
	#[\JMS\Serializer\Annotation\SerializedName('recordDueDate')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $recordDueDate = null;
    
    /**
     * The moment this Risk Cloud resource was last updated measured in milliseconds since the Unix epoch.
     * 
     * @var ?\DateTime $updated
     */
	#[\JMS\Serializer\Annotation\SerializedName('updated')]
    #[\JMS\Serializer\Annotation\Type("DateTime<'Y-m-d\TH:i:s.up'>")]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?\DateTime $updated = null;
    
	public function __construct()
	{
		$this->completed = null;
		$this->created = null;
		$this->daysUntilDue = null;
		$this->dueDate = null;
		$this->lastCompleted = null;
		$this->recordDueDate = null;
		$this->updated = null;
	}
}
