<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Components;


/** The status of the record */
enum Status: string
{
    case Inactive = 'INACTIVE';
    case NotAssigned = 'NOT_ASSIGNED';
    case Assigned = 'ASSIGNED';
    case InProgress = 'IN_PROGRESS';
    case Complete = 'COMPLETE';
}
