<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Components;


/**
 * StepPropertyApiOut - The origin step of the record
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Components
 * @access public
 */
class StepPropertyApiOut
{
    /**
     * The unique ID of this Risk Cloud resource
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * The name of the step
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Identifies the type of object this data represents
     * 
     * @var ?string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $object = null;
    
    /**
     * The type of the step
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Components\StepPropertyApiOutType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Components\StepPropertyApiOutType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StepPropertyApiOutType $type = null;
    
	public function __construct()
	{
		$this->id = null;
		$this->name = null;
		$this->object = null;
		$this->type = null;
	}
}
