<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Components;


/**
 * StepApiUpdateIn - Step (Update)
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Components
 * @access public
 */
class StepApiUpdateIn
{
    /**
     * Indicates which users are allowed to be assigned this step on a record
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Components\StepApiUpdateInAssignableUserType $assignableUserType
     */
	#[\JMS\Serializer\Annotation\SerializedName('assignableUserType')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Components\StepApiUpdateInAssignableUserType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StepApiUpdateInAssignableUserType $assignableUserType = null;
    
    /**
     * Whether comments are displayed on a step
     * 
     * @var ?bool $enableComments
     */
	#[\JMS\Serializer\Annotation\SerializedName('enableComments')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $enableComments = null;
    
    /**
     * Whether MFA is required for external users to access this step.
     * 
     * @var ?bool $externalUserMfaRequired
     */
	#[\JMS\Serializer\Annotation\SerializedName('externalUserMfaRequired')]
    #[\JMS\Serializer\Annotation\Type('bool')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?bool $externalUserMfaRequired = null;
    
    /**
     * The name of the step
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * The type of the step (for END steps, this property cannot be updated since there would be no outgoing default next paths)
     * 
     * @var ?\speakeasy_bar-test\Risk-Cloud-API\Models\Components\StepApiUpdateInType $type
     */
	#[\JMS\Serializer\Annotation\SerializedName('type')]
    #[\JMS\Serializer\Annotation\Type('enum<speakeasy_bar-test\Risk-Cloud-API\Models\Components\StepApiUpdateInType>')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?StepApiUpdateInType $type = null;
    
    /**
     * The x-coordinate of the step in the application builder (must not be less than 0)
     * 
     * @var ?int $xpos
     */
	#[\JMS\Serializer\Annotation\SerializedName('xpos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $xpos = null;
    
    /**
     * The y-coordinate of the step in the application builder (must not be less than 0)
     * 
     * @var ?int $ypos
     */
	#[\JMS\Serializer\Annotation\SerializedName('ypos')]
    #[\JMS\Serializer\Annotation\Type('int')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?int $ypos = null;
    
	public function __construct()
	{
		$this->assignableUserType = null;
		$this->enableComments = null;
		$this->externalUserMfaRequired = null;
		$this->name = null;
		$this->type = null;
		$this->xpos = null;
		$this->ypos = null;
	}
}
