<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Components;


/** The type of the step */
enum StepPropertyApiOutType: string
{
    case Origin = 'ORIGIN';
    case Chain = 'CHAIN';
    case End = 'END';
}
