<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API\Models\Components;


/**
 * WorkflowPropertyApiOut - The parent workflow of the step
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API\Models\Components
 * @access public
 */
class WorkflowPropertyApiOut
{
    /**
     * The unique ID of this Risk Cloud resource
     * 
     * @var ?string $id
     */
	#[\JMS\Serializer\Annotation\SerializedName('id')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $id = null;
    
    /**
     * The name of the workflow
     * 
     * @var ?string $name
     */
	#[\JMS\Serializer\Annotation\SerializedName('name')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $name = null;
    
    /**
     * Identifies the type of object this data represents
     * 
     * @var ?string $object
     */
	#[\JMS\Serializer\Annotation\SerializedName('object')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $object = null;
    
    /**
     * The prefix to be used in the name of every record created from this workflow
     * 
     * @var ?string $recordPrefix
     */
	#[\JMS\Serializer\Annotation\SerializedName('recordPrefix')]
    #[\JMS\Serializer\Annotation\Type('string')]
    #[\JMS\Serializer\Annotation\SkipWhenEmpty]
    public ?string $recordPrefix = null;
    
	public function __construct()
	{
		$this->id = null;
		$this->name = null;
		$this->object = null;
		$this->recordPrefix = null;
	}
}
