<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API;

class Authentication 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * Create an API Access Token
     * 
     * **Permissions:** Authenticated User
     * 
     * Generates a new, expiring access token from the provided Client and Secret keys.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\GetApiTokenRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\GetApiTokenResponse
     */
	public function getApiToken(
        ?\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\GetApiTokenRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\GetApiTokenResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v1/account/token');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $statusCode = $httpResponse->getStatusCode();

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\GetApiTokenResponse();
        $response->statusCode = $statusCode;
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->legacyApiTokenOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Components\LegacyApiTokenOut', 'json');
            }
        }

        return $response;
    }
}