<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API;

/**
 * RiskCloudAPI - Risk Cloud API: Welcome to the Risk Cloud API v2! This is a collection of new API-first and RESTful API endpoints to streamline the creation of custom integrations with the Risk Cloud.
 * 
 * 
 * **Note**: These endpoints are currently in **open alpha**, meaning that backwards compatibility is not guaranteed and breaking changes are to be expected as the endpoints are finalized. The full release of these new v2 endpoints is anticipated for late 2023.
 * 
 * For our existing collections of v1 endpoints, 
 * please feel free to reference [Risk Cloud API v1](https://docs.logicgate.com).
 * https://www.logicgate.com/developer/ - Developer Portal
 * 
 * @package speakeasy_bar-test\Risk-Cloud-API
 * @access public
 * @see https://www.logicgate.com/developer/
 */
class RiskCloudAPI
{
	public const SERVERS = [
		'http://localhost',
	];
  	
    /**
     * An [Application](https://help.logicgate.com/hc/en-us/articles/4402674055572-Create-a-new-Application) is a collection of Workflows, Steps, and logic that collectively solve a business use case
     * 
     * @var Application $$application
     */
	public Application $application;
	
    /**
     * Getting Started: How to create an [API Access Token](https://www.logicgate.com/developer/risk-cloud-api-authentication/) to begin integrating with the Risk Cloud API
     * 
     * @var Authentication $$authentication
     */
	public Authentication $authentication;
	
    /**
     * A [Field](https://help.logicgate.com/hc/en-us/articles/4402674064020-Create-Fields) is used to capture information from and display information to users in a Workflow
     * 
     * @var Field $$field
     */
	public Field $field;
	
    /**
     * A [Record](https://help.logicgate.com/hc/en-us/articles/4402683104020-Complete-a-Record) is a form that can capture information, store cataloged data, and link to other Records as it moves through each Step of a Workflow
     * 
     * @var Record $$record
     */
	public Record $record;
	
    /**
     * A [Step](https://help.logicgate.com/hc/en-us/articles/4402674059668-Create-a-Step) lives in a Workflow and is configured with a set of Sections, Subsections and Fields to create a form
     * 
     * @var Step $$step
     */
	public Step $step;
	
    /**
     * A [Workflow](https://help.logicgate.com/hc/en-us/articles/4402683108756-Create-a-new-Workflow) is a combination of Steps, Paths, Fields, and routing logic that combine to form a system in an Application
     * 
     * @var Workflow $$workflow
     */
	public Workflow $workflow;
	
    /**
     * A [Workflow Map](https://help.logicgate.com/hc/en-us/articles/4402683117588) represents a relationship between two Workflows
     * 
     * @var WorkflowMap $$workflowMap
     */
	public WorkflowMap $workflowMap;
		
	private SDKConfiguration $sdkConfiguration;

	/**
	 * Returns a new instance of the SDK builder used to configure and create the SDK instance.
	 * 
	 * @return RiskCloudAPIBuilder
	 */
	public static function builder(): RiskCloudAPIBuilder
	{
		return new RiskCloudAPIBuilder();
	}

	/**
	 * @param SDKConfiguration $sdkConfiguration
	 */
	public function __construct(SDKConfiguration $sdkConfiguration)
	{
		$this->sdkConfiguration = $sdkConfiguration;
		
		$this->application = new Application($this->sdkConfiguration);
		
		$this->authentication = new Authentication($this->sdkConfiguration);
		
		$this->field = new Field($this->sdkConfiguration);
		
		$this->record = new Record($this->sdkConfiguration);
		
		$this->step = new Step($this->sdkConfiguration);
		
		$this->workflow = new Workflow($this->sdkConfiguration);
		
		$this->workflowMap = new WorkflowMap($this->sdkConfiguration);
	}
}