<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API;

class Step 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * Create a step
     * 
     * **Permissions:** [Build Access to parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Create a step from a JSON request body.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateStepRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateStepResponse
     */
	public function create(
        \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateStepRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateStepResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/steps');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "stepApiCreateIn", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateStepResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->stepApiOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiOut', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Delete a step
     * 
     * **Permissions:** [Build Access to parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Delete a step specified by the ID in the URL path.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteStepRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteStepResponse
     */
	public function delete(
        ?\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteStepRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteStepResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/steps/{id}', \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteStepRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('DELETE', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteStepResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->appActionResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\AppActionResponse', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Retrieve a step
     * 
     * **Permissions:** [Build Access to parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Retrieve a step specified by the ID in the URL path.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadStepRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadStepResponse
     */
	public function read(
        ?\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadStepRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadStepResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/steps/{id}', \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadStepRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadStepResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->stepApiOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiOut', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Retrieve steps
     * 
     * **Permissions:** [Build Access](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Retrieve a page of all steps that the current user has [Build Access to parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications) to.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllStepsRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllStepsResponse
     */
	public function readAll(
        ?\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllStepsRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllStepsResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/steps');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllStepsRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllStepsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->pageModelOutStepApiOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\PageModelOutStepApiOut', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Update a step
     * 
     * **Permissions:** [Build Access to parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Update a step specified by the ID in the URL path from a JSON request body. Only present properties with non-empty values are updated.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateResponse
     */
	public function update(
        \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/steps/{id}', \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateRequest::class, $request);
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "stepApiUpdateIn", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('PATCH', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->stepApiOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\StepApiOut', 'json');
            }
        }

        return $response;
    }
}