<?php

/**
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

declare(strict_types=1);

namespace speakeasy_bar-test\Risk-Cloud-API;

class WorkflowMap 
{

	private SDKConfiguration $sdkConfiguration;

	/**
	 * @param SDKConfiguration $sdkConfig
	 */
	public function __construct(SDKConfiguration $sdkConfig)
	{
		$this->sdkConfiguration = $sdkConfig;
	}
	
    /**
     * Create a workflow map
     * 
     * **Permissions:** [Build Access to parent applications](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Create a workflow map from a JSON request body.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateWorkflowMapRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateWorkflowMapResponse
     */
	public function create(
        \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateWorkflowMapRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateWorkflowMapResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/workflow-maps');
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "workflowMapApiCreateIn", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('POST', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\CreateWorkflowMapResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->workflowMapApiOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiOut', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Delete a workflow map
     * 
     * **Permissions:** [Build Access to a parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Delete a workflow map specified by the ID in the URL path.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteWorkflowMapRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteWorkflowMapResponse
     */
	public function delete(
        ?\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteWorkflowMapRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteWorkflowMapResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/workflow-maps/{id}', \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteWorkflowMapRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('DELETE', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\DeleteWorkflowMapResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->appActionResponse = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\AppActionResponse', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Retrieve a workflow map
     * 
     * **Permissions:** [Build Access to a parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Retrieve a workflow map specified by the ID in the URL path.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadWorkflowMapRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadWorkflowMapResponse
     */
	public function read(
        ?\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadWorkflowMapRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadWorkflowMapResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/workflow-maps/{id}', \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadWorkflowMapRequest::class, $request);
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadWorkflowMapResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->workflowMapApiOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiOut', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Retrieve workflow maps
     * 
     * **Permissions:** [Build Access](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Retrieve a page of all workflow maps that the current user has [Build Access to a parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications) to.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllWorkflowMapsRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllWorkflowMapsResponse
     */
	public function readAll(
        ?\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllWorkflowMapsRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllWorkflowMapsResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/workflow-maps');
        
        $options = ['http_errors' => false];
        $options = array_merge_recursive($options, Utils\Utils::getQueryParams(\speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllWorkflowMapsRequest::class, $request, null));
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('GET', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\ReadAllWorkflowMapsResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->pageModelOutWorkflowMapApiOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\PageModelOutWorkflowMapApiOut', 'json');
            }
        }

        return $response;
    }
	
    /**
     * Update a workflow map
     * 
     * **Permissions:** [Build Access to a parent application](https://help.logicgate.com/hc/en-us/articles/4402683190164-Control-Build-Access-for-Applications)
     * 
     * Update a workflow map specified by the ID in the URL path from a JSON request body. Only present properties with non-empty values are updated.
     * 
     * @param \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateWorkflowMapRequest $request
     * @return \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateWorkflowMapResponse
     */
	public function update(
        \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateWorkflowMapRequest $request,
    ): \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateWorkflowMapResponse
    {
        $baseUrl = $this->sdkConfiguration->getServerUrl();
        $url = Utils\Utils::generateUrl($baseUrl, '/api/v2/workflow-maps/{id}', \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateWorkflowMapRequest::class, $request);
        
        $options = ['http_errors' => false];
        $body = Utils\Utils::serializeRequestBody($request, "workflowMapApiUpdateIn", "json");
        if ($body === null) {
            throw new \Exception('Request body is required');
        }
        $options = array_merge_recursive($options, $body);
        $options = array_merge_recursive($options, Utils\Utils::getHeaders($request));
        if (!array_key_exists('headers', $options)) {
            $options['headers'] = [];
        }
        $options['headers']['Accept'] = 'application/json';
        $options['headers']['user-agent'] = $this->sdkConfiguration->userAgent;
        
        $httpResponse = $this->sdkConfiguration->securityClient->request('PATCH', $url, $options);
        
        $contentType = $httpResponse->getHeader('Content-Type')[0] ?? '';

        $response = new \speakeasy_bar-test\Risk-Cloud-API\Models\Operations\UpdateWorkflowMapResponse();
        $response->statusCode = $httpResponse->getStatusCode();
        $response->contentType = $contentType;
        $response->rawResponse = $httpResponse;
        
        if ($httpResponse->getStatusCode() === 200) {
            if (Utils\Utils::matchContentType($contentType, 'application/json')) {
                $serializer = Utils\JSON::createSerializer();
                $response->workflowMapApiOut = $serializer->deserialize((string)$httpResponse->getBody(), 'speakeasy_bar-test\Risk-Cloud-API\Models\Shared\WorkflowMapApiOut', 'json');
            }
        }

        return $response;
    }
}